#include <bits/stdc++.h>

using namespace std;

class Solution {
    public:
        void test_cases() {
            
            return;
        }
};

signed main(void) {
    if (1) {
        ios_base::sync_with_stdio(false);
        cin.tie(nullptr);
        cout.tie(0);
    }

    int t;
    cin >> t;
    Solution run;
        while (t--) {
            run.test_cases();
        }
    return 0;
}